language: php
php:
  - 7.4

before_script:
  - pecl install -f mongodb-stable
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer update

services:
  - mongodb

script:
  - composer test-coverage-u
